export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const PURCHASEABLE = "PURCHASEABLE";
export const RESET_INGREDIENTS = "RESET_INGREDIENTS";

export const ORDER_LOAD = "ORDER_LOAD";
export const LOADING_ORDER = "LOADING_ORDER";
