export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const PURCHASEABLE = "PURCHASEABLE";
export const RESET_INGREDIENTS = "RESET_INGREDIENTS";
